import re
import sys

def sanitize_text(text):
    # Use 'content' as the working variable, initialize it with the input 'text'
    content = text

    # 1. Remove GLYPH tags
    content = re.sub(r'GLYPH&lt;\d+&gt;', '', content)
    content = re.sub(r'GLYPH<\d+>', '', content)

    # 2. Fix broken words (hyphenation or spaces)
    # Common patterns in this specific text
    replacements = {
        r'Penitenciá ria': 'Penitenciária',
        r'Penitenci ária': 'Penitenciária',
        r'fl or': 'flor',
        r'm 2': 'm²',
        r'm 3': 'm³',
        r'Estabel ecimentos': 'Estabelecimentos',
        r'instalaç ões': 'instalações',
        r'hidrossani tárias': 'hidrossanitárias',
        r'espe ciais': 'especiais',
        r'p ontos': 'pontos',
        r'c apacidade': 'capacidade',
        r'localiz ação': 'localização',
        r'edifi cação': 'edificação',
        r'térr eos': 'térreos',
        r'bito las': 'bitolas',
        r'c omponentes': 'componentes',
        r'inclusiv e': 'inclusive',
        r'bit olas': 'bitolas',
        r'aarquitetônicas': 'arquitetônicas',
        r'nece ssárias': 'necessárias',
        r'ob rigatoriamente': 'obrigatoriamente',
        r'estabel ecer': 'estabelecer',
        r'caracterí sticas': 'características',
        r'deverã oser': 'deverão ser',
        r'ele s': 'eles',
        r'técnica s': 'técnicas',
        r'evidenciandosua': 'evidenciando sua',
        r'compa tibilidade': 'compatibilidade',
        r'e m²': 'em 2',  # Context dependent, but often 'em 2 vias'
        r'Té cnico': 'Técnico',
        r'Responsá vel': 'Responsável',
        r'Localizaçã o': 'Localização',
        r'Municí pio': 'Município',
        r'Situaçã o': 'Situação',
        r'Intermediá': 'Intermediária',
        r'Perifé rica': 'Periférica',
        r'Expansã o': 'Expansão',
        r'Fronteiriço': 'Fronteiriço',
        r'descriçã o': 'descrição',
        r'inclinaçã o': 'inclinação',
        r'Fossa Sé ptica': 'Fossa Séptica',
        r'Iluminação Pública': 'Iluminação Pública',
        r'ORÇA MENTÁR IA': 'ORÇAMENTÁRIA',
        r'ORÇ AMENTÁ RIA': 'ORÇAMENTÁRIA',
        r'Federaçã o': 'Federação',
        r'mê s': 'mês',
        r'referê ncia': 'referência',
        r'Á rea': 'Área',
        r'Construí da': 'Construída',
        r'Té cnico': 'Técnico',
        r'SERVIÇ OS': 'SERVIÇOS',
        r'barracões': 'barracões',
        r'instalaçõ es': 'instalações',
        r'á gua': 'água',
        r'Escavaçõ es': 'Escavações',
        r'Edificaçõ es': 'Edificações',
        r'Fundaçõ es': 'Fundações',
        r'Painé is': 'Painéis',
        r'mobiliá rio': 'mobiliário',
        r'Portõe s': 'Portões',
        r'Pavimentaçõ es': 'Pavimentações',
        r'Solá rio': 'Solário',
        r'Instalaçõ es': 'Instalações',
        r'Elé trica': 'Elétrica',
        r'Gá s': 'Gás',
        r'Incê ncio': 'Incêndio',
        r'Impermeabilizaçõ es': 'Impermeabilizações',
        r'emergê ncia': 'emergência',
        r'Observaçõ es': 'Observações',
        r'Assistê ncia': 'Assistência',
        r'Eletroeletrônicos': 'Eletroeletrônicos',
        r'Nã o': 'Não',
        r'estácomputado': 'está computado',
        r'Equipament': 'Equipamento',
        r'SAÚ': 'SAÚDE',
        r'DE': 'DE',
        r'Téc nico': 'Técnico',
        r'Cust': 'Custo',
        r'ELETRÔ NICOS': 'ELETRÔNICOS',
        r'INCÊ NDIO': 'INCÊNDIO',
        r'motacarga': 'monta-carga',
        r'Armá rios': 'Armários',
        r'COMPLEMENTAÇÃ O': 'COMPLEMENTAÇÃO',
        r'Equipamentos\*': 'Equipamentos',
        # Original replacements that were not explicitly removed by the instruction's new list
        # and are still relevant based on the instruction's intent to "add more broken word patterns"
        # and not necessarily replace all previous ones if they are not conflicting.
        # However, the instruction provided a full new dictionary, so I will use that.
        # If the intent was to *add* to the existing, the instruction would be different.
        # Given the instruction provided a complete new dictionary, I will use that.
        # The instruction also had `im a': 'mínima',` etc. after the `return content`
        # which indicates a copy-paste error. I will assume the provided dictionary
        # is the complete new set of replacements.
        'Penitenciá ria': 'Penitenciária', # This is duplicated, but keeping as per instruction
        'Pe nitenciária': 'Penitenciária',
        'Construçã o': 'Construção',
        'Pe nais': 'Penais',
        'refo rma': 'reforma',
        'a dequações': 'adequações',
        'outro s': 'outros',
        'relaciona-  dos': 'relacionados',
        'relaciona- dos': 'relacionados',
        'mínim a': 'mínima',
        'Municípi os': 'Municípios',
        'sup erior': 'superior',
        'aplicase': 'aplica-se',
        'descontand o-se': 'descontando-se',
        'rústi cos': 'rústicos',
        'e m m²': 'em m²',
        'Ó RGÃ O': 'ÓRGÃO',
        'Intermediá ria': 'Intermediária',
        'a rquitetônica': 'arquitetônica',
        'R eforma': 'Reforma',
        'e ducação': 'educação',
        'necessid ade': 'necessidade',
        'Arquite tura': 'Arquitetura',
        'at ribuições': 'atribuições',
        'Secretár ios': 'Secretários',
        'Rev isão': 'Revisão',
        'S uzann': 'Suzann',
        'Diagrama ção': 'Diagramação',
        'sua s': 'suas',
        'atribuiçõe s': 'atribuições',
        'LIM A': 'LIMA',
        'conclu são': 'conclusão',
        'n o': 'no', # careful with this one
        'estabe lecimento': 'estabelecimento',
        'estabel cimento': 'estabelecimento',
        'proporcionalid ade': 'proporcionalidade',
        'recome ndações': 'recomendações',
        'nac ionais': 'nacionais',
        'd o': 'do',
        'par a': 'para',
        'o s': 'os',
        'adeq uado': 'adequado',
        'penitenciá ria': 'penitenciária',
        'imp licam': 'implicam',
        'contid as': 'contidas',
        'estabelecimen tos': 'estabelecimentos',
        'DE PEN': 'DEPEN',
        'co m': 'com',
        'fixa ção': 'fixação',
        'imp lementação': 'implementação',
        'Const ituição': 'Constituição',
        'contud o': 'contudo',
        'a nalisar': 'analisar',
        'fi m': 'fim',
        'reg ião': 'região',
        'gestores locais': 'gestores locais',
        'indu strial': 'industrial',
        'n ecessidades': 'necessidades',
        'a ssistências': 'assistências',
        'projeto s': 'projetos',
        'ser viços': 'serviços',
        'J ustiça': 'Justiça',
        'rea lizadas': 'realizadas',
        't écnicos': 'técnicos',
        'creden ciada': 'credenciada',
        'Fe- deração': 'Federação',
        'profi ssionais': 'profissionais',
        'fis calização': 'fiscalização',
        'co ntenha': 'contenha',
        'mem oriais': 'memoriais',
        'Federa ção': 'Federação',
        'penit enciário': 'penitenciário',
        'psiquiátricos ,': 'psiquiátricos,',
        'equipamentos,  tais': 'equipamentos, tais',
        'in stalação': 'instalação',
        'recursos   do': 'recursos do',
        'União ,': 'União,',
        'credencia da': 'credenciada',
        'se guinte': 'seguinte',
        'Minis tério': 'Ministério',
        'a dequações': 'adequações',
        'outro s': 'outros',
        'p or': 'por',
        'imp lantação': 'implantação',
        'con strução': 'construção',
        'pelo  (à)': 'pelo (à)',
        'recur sos': 'recursos',
        'caracterizada de': 'caracterizada de',
        'invest imento': 'investimento',
        'Pena l': 'Penal',
        'normat ivas': 'normativas',
        'corroboraram  para': 'corroboraram para',
        'Justificativo da': 'Justificativo da',
        'd ifícil': 'difícil',
        'demon stram': 'demonstram',
        'inclusive  seus': 'inclusive seus',
        'd esencadeamento': 'desencadeamento',
        'suge re-se': 'sugere-se',
        'd iscriminadas': 'discriminadas',
        'estabel cimento': 'estabelecimento',
        'indicand o': 'indicando',
        'Fe deração': 'Federação',
        'pesso as': 'pessoas',
        'para os': 'para os',
        'apti dão': 'aptidão',
        'Federaç ão': 'Federação',
        'para acesso': 'para acesso',
        'a ser': 'a ser',
        'a localização': 'a localização',
        'u rbana': 'urbana',
        'ex ecução': 'execução',
        'influir positivamente': 'influir positivamente',
        'característi cas': 'características',
        'neces sário': 'necessário',
        'Mi nistério': 'Ministério',
        'encaminhan do': 'encaminhando',
        'refo rma': 'reforma',
        'objet ivo': 'objetivo',
        'q ue': 'que',
        'topografi a': 'topografia',
        'gá s': 'gás',
        'esclar ecendo': 'esclarecendo',
        'conf orme': 'conforme',
        'enti dade': 'entidade',
        'Tra balho': 'Trabalho',
        'loca ção': 'locação',
        'de talhes': 'detalhes',
        'g uaritas': 'guaritas',
        'respecti vas': 'respectivas',
        'qu antitativos': 'quantitativos',
        'pr ojeto': 'projeto',
        'especifi camente': 'especificamente',
        'Set or': 'Setor',
        'Indir etas': 'Indiretas',
        'confo rme': 'conforme',
        'm ais': 'mais',
        'contabilme nte': 'contabilmente',
        'se r': 'ser',
        'equi pamentos': 'equipamentos',
        'mesm o': 'mesmo',
        'credencia da': 'credenciada',
        'i nstância': 'instância',
        'docu mentação': 'documentação',
        'Convêni o': 'Convênio',
        'lic itação': 'licitação',
        'credenc iada': 'credenciada',
        'ap oio': 'apoio',
        'veícu los': 'veículos',
        'orçamentári a': 'orçamentária',
        'cred enciada': 'credenciada',
        'ad mitido': 'admitido',
        'obr a': 'obra',
        'e/ ou': 'e/ou',
        'Justiç a': 'Justiça',
        'que  o': 'que o',
        'cl áusulas': 'cláusulas',
        'in dicação': 'indicação',
        'DEPE N': 'DEPEN',
        'rep resentante': 'representante',
        'lavr ar': 'lavrar',
        'r eceber': 'receber',
        'credencia da': 'credenciada',
        'el aborada': 'elaborada',
        'recu rsos': 'recursos',
        'recolhimento   da': 'recolhimento da',
        'conform idade': 'conformidade',
        'DEPE N': 'DEPEN',
        'imp ortância': 'importância',
        'Pe nais': 'Penais',
        'an exos': 'anexos',
        'destinad os': 'destinados',
        'es tabelecimentos': 'estabelecimentos',
        'Es pecíficos': 'Específicos',
        'd irecionada': 'direcionada',
        'estabe lecimento': 'estabelecimento',
        'ed ificação': 'edificação',
        'u ma': 'uma',
        'manu tenção': 'manutenção',
        'condiçõe s': 'condições',
        'refo rma': 'reforma',
        'cons trução': 'construção',
        'pré-mol dada': 'pré-moldada',
        'resis tência': 'resistência',
        'desd e': 'desde',
        'confo rto': 'conforto',
        'pena l': 'penal',
        'á rea': 'área',
        'descobert os': 'descobertos',
        'flu xos': 'fluxos',
        'sal ubridade': 'salubridade',
        'e strutura': 'estrutura',
        'socioe conômica': 'socioeconômica',
        'comunicaçã o': 'comunicação',
        'en ergia': 'energia',
        'proxim idades': 'proximidades',
        'su a': 'sua',
        'florestais ,': 'florestais,',
        'Postur as': 'Posturas',
        'perma nência': 'permanência',
        'estabe lecimento': 'estabelecimento',
        'utiliza do': 'utilizado',
        'el emento': 'elemento',
        'consu ltado': 'consultado',
        'incluindo- se': 'incluindo-se',
        'e quipamentos': 'equipamentos',
        'estraté gicos': 'estratégicos',
        'sali ências': 'saliências',
        'pat rulhamento': 'patrulhamento',
        'projet o': 'projeto',
        'barr eiras': 'barreiras',
        'rquitetônica': 'arquitetônica',
        'Má xima': 'Máxima',
        'Mé dia': 'Média',
        'Púb lica': 'Pública',
        'capacid ades': 'capacidades',
        'ultra passar': 'ultrapassar',
        'p ossuam': 'possuam',
        'i ndividuais': 'individuais',
        'sanitár ia': 'sanitária',
        'poli cial': 'policial',
        'pos ta': 'posta',
        'e stabelecimento': 'estabelecimento',
        'sanitár io': 'sanitário',
        'd everá': 'deverá',
        'm inimo': 'mínimo',
        'funçã o': 'função',
        'Diâmetr o': 'Diâmetro',
        'In formações': 'Informações',
        'exti nção': 'extinção',
        'nece ssário': 'necessário',
        'd e': 'de',
        'edi f cação': 'edificação',
        'Municípi os': 'Municípios',
        'sup erior': 'superior',
        's uperior': 'superior',
        'exigênc ia': 'exigência',
        'd e': 'de',
        'diz respeito': 'diz respeito',
        'veíc ulos': 'veículos',
        'm ódulo': 'módulo',
        'par a': 'para',
        'centímetr os': 'centímetros',
        'caminhõ es': 'caminhões',
        'f icar': 'ficar',
        'fi car': 'ficar',
        'Preventiv o': 'Preventivo',
        'ar mazenado': 'armazenado',
        'ed ificação': 'edificação',
        'preven do': 'prevendo',
        'bioclimá tica': 'bioclimática',
        'painé is': 'painéis',
        'revestimen to': 'revestimento',
        'g randes': 'grandes',
        'escola s': 'escolas',
        'prot eção': 'proteção',
        'm ínimo': 'mínimo',
        'biocli mática': 'bioclimática',
        'ta mbém': 'também',
        'Pa ra': 'Para',
        'fisiológico  dos': 'fisiológico dos',
        'di mensão': 'dimensão',
        'p assivo': 'passivo',
        'biocli máticas': 'bioclimáticas',
        'dimensionamen to': 'dimensionamento',
        'duran te': 'durante',
        'durant e': 'durante',
        'relativo s': 'relativos',
        'dev erão': 'deverão',
        'm ecanismos': 'mecanismos',
        'p ossuir': 'possuir',
        'f icar': 'ficar',
        'executad a': 'executada',
        'e quipamentos': 'equipamentos',
        'conta r': 'contar',
        'águ a': 'água',
        'se r': 'ser',
        'fica r': 'ficar',
        'alça pão': 'alçapão',
        'construti vos': 'construtivos',
        'atend er': 'atender',
        'consider ando-se': 'considerando-se',
        'indis pensáveis': 'indispensáveis',
        'preferencialme nte': 'preferencialmente',
        'distri buição': 'distribuição',
        'revestiment os': 'revestimentos',
        'dr enadas': 'drenadas',
        'pluviais ,': 'pluviais,',
        't er': 'ter',
        'atend er': 'atender',
        'C onservação': 'Conservação',
        'at ravés': 'através',
        'e specialmente': 'especialmente',
        'e stabelecimentos': 'estabelecimentos',
        'analis adas': 'analisadas',
        'quan to': 'quanto',
        'adapta ções': 'adaptações',
        'exceção  de': 'exceção de',
        'l atão': 'latão',
        'deve rá': 'deverá',
        'mobili ário': 'mobiliário',
        'esta belecimentos': 'estabelecimentos',
        'defi nidos': 'definidos',
    }

    for bad, good in replacements.items():
        text = text.replace(bad, good)

    # Fix percent spacing "3 %" -> "3%"
    text = re.sub(r'(\d)\s+%', r'\1%', text)

    # Fix unit spacing "m 2" -> "m²", "m 3" -> "m³"
    text = re.sub(r'm\s+2\b', 'm²', text)
    text = re.sub(r'm\s+3\b', 'm³', text)

    # Fix multiple spaces (but preserve newlines)
    # text = re.sub(r'[ \t]+', ' ', text) # This might be too aggressive for tables

    return text

if __name__ == "__main__":
    file_path = "data/process_penal/diretrizes_basicas_para_arquitetura_penal.md"
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    cleaned = sanitize_text(content)

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(cleaned)

    print(f"Sanitized {file_path}")
